/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controller.utilidades.Utiles;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import vistasmodeloTabla.MTableEmpresa;

/**
 *
 * @author InnoVausuario
 */
public class FrmEmpresa extends javax.swing.JDialog {

    MTableEmpresa mTableEmpresa = new MTableEmpresa();
    private Empresa empresa ; // un arreglo de objetos de tipo empresa 
    private Integer anio;
    private Integer fila = -1; // modificar un dato en la tabla 

    public FrmEmpresa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();// Instanciar objetos por ende no retorna nada
        utilesVistas.cargarAnios(cbxnumero);

    }

    private void cargarTabla() {
        mTableEmpresa.setEmpresa(empresa);
        tbltabla.setModel(mTableEmpresa);
        tbltabla.updateUI();
    }

    // verficar la entrada de datos 
    private boolean verificar() {
        return (txtVentas.getText().trim().isEmpty() || txtGastos.getText().trim().isEmpty());

    }

    // limpiar la vista 
    private void limpiar() {
        txtVentas.setText("");
        txtGastos.setText("");
        lblPromedioTotal.setText("PROMEDIO:   0.0");
        cargarTabla();
        tbltabla.clearSelection();

    }

    private void registrar() {
        if (verificar()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos ");
        } else {
            if (Utiles.validate(txtGastos.getText().trim()) && Utiles.validate(txtVentas.getText().trim())) {
                Float gastos = Utiles.transformarFloat(txtGastos.getText().trim());
                Float ventas = Utiles.transformarFloat(txtVentas.getText().trim());
                if (fila == -1) {
                    if (empresa.guardar(ventas, gastos)) {
                        JOptionPane.showMessageDialog(null, "Se ha registrado correctamente", "OK!", JOptionPane.INFORMATION_MESSAGE);
                        limpiar();
                    } else {
                        JOptionPane.showMessageDialog(null, "Hubo un error al guardar o ya se guardaron los alumnos", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {

                    if (empresa.modificar(ventas, gastos, fila)) {
                        JOptionPane.showMessageDialog(null, "Se ha modificado correctamente!!", "OK!", JOptionPane.INFORMATION_MESSAGE);
                        limpiar();
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al modificar", "ERROR", JOptionPane.ERROR);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese un número", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }

    private void cargarDatos() {
        fila = tbltabla.getSelectedRow();
        if (fila >= 0) {
            if (empresa.getDatos()[0][fila].toString() != null && empresa.getDatos()[1][fila].toString() != null) {
                txtVentas.setText(empresa.getDatos()[0][fila].toString());
                txtGastos.setText(empresa.getDatos()[1][fila].toString());
            } else {
                fila = -1;
                txtVentas.setText("");
                txtGastos.setText("");
                JOptionPane.showMessageDialog(null, "Seleccione un registro Valido", "ERROR", JOptionPane.ERROR);
            }
        } else {
            fila = -1;
            JOptionPane.showMessageDialog(null, "Llene todos los datos", "ERROR", JOptionPane.ERROR);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. initComponents();
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxnumero = new javax.swing.JComboBox<>();
        btngenrar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtVentas = new java.awt.TextField();
        txtGastos = new java.awt.TextField();
        btnAgregar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltabla = new javax.swing.JTable();
        lblTotalGastos = new javax.swing.JLabel();
        lblTotalVentas = new javax.swing.JLabel();
        btnSelec = new javax.swing.JButton();
        btnInforme = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblPromedioTotal = new javax.swing.JLabel();
        lblGastosAltos = new javax.swing.JLabel();
        lblVentasAltas = new javax.swing.JLabel();
        lblVentasBajas = new javax.swing.JLabel();
        lblGastosBajos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear informe: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Seleccione el año del informe ");

        cbxnumero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        cbxnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxnumeroActionPerformed(evt);
            }
        });

        btngenrar.setText("Confirmar");
        btngenrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(cbxnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(btngenrar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btngenrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ingrese las notas"));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Ventas mensuales totales:  ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Gastos mensuales totales ");

        txtVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVentasActionPerformed(evt);
            }
        });

        txtGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGastosActionPerformed(evt);
            }
        });

        btnAgregar.setText("AGREGAR");
        btnAgregar.setEnabled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(57, 57, 57)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtGastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Calendario :"));

        tbltabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Enero", null, null},
                {"Febrero", null, null},
                {"Marzo", null, null},
                {"Abril", null, null},
                {"Mayo", null, null},
                {"Junio", null, null},
                {"Julio", null, null},
                {"Agosto", null, null},
                {"Septiembre", null, null},
                {"Octubre", null, null},
                {"Noviembre", null, null},
                {"Diciembre", null, null}
            },
            new String [] {
                "MES", "VENTA", "GASTO"
            }
        ));
        jScrollPane1.setViewportView(tbltabla);

        lblTotalGastos.setText("TOTAL GASTOS: ");

        lblTotalVentas.setText("TOTAL VENTAS: ");

        btnSelec.setBackground(new java.awt.Color(153, 153, 255));
        btnSelec.setText("SELECIONAR");
        btnSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecActionPerformed(evt);
            }
        });

        btnInforme.setBackground(new java.awt.Color(153, 153, 255));
        btnInforme.setText("INFORME");
        btnInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformeActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setText("CARGAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblPromedioTotal.setText("PROMEDIO: ");

        lblGastosAltos.setText("GASTOS ALTOS: ");

        lblVentasAltas.setText("VENTAS ALTAS: ");

        lblVentasBajas.setText("VENTAS BAJAS: ");

        lblGastosBajos.setText("GASTOS BAJOS: ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSelec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(389, 389, 389)
                                .addComponent(lblVentasBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(lblVentasAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblGastosAltos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblGastosBajos, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblTotalGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPromedioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnSelec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInforme))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblVentasAltas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblVentasBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGastosAltos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGastosBajos, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(8, 8, 8)
                        .addComponent(lblPromedioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblTotalGastos)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jLabel4.setBackground(new java.awt.Color(0, 51, 204));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("INFORME");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngenrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenrarActionPerformed
        // TODO add your handling code here:
        //crearArreglos();
        anio = cbxnumero.getSelectedIndex();// posicion que ocupa cada año en el cbx 
        empresa= new Empresa(); // crear cada vez que vas a usar
        empresa.crear();// objeto de tipo empresa en la posicion 
        btnAgregar.setEnabled(true);
        cargarTabla();
    }//GEN-LAST:event_btngenrarActionPerformed

    private void cbxnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxnumeroActionPerformed

    private void txtVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVentasActionPerformed

    private void txtGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGastosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGastosActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:

        registrar();
        cargarTabla();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        Object seleccion = cbxnumero.getItemAt(anio);
        if (empresa.cargarArchivo((Integer) seleccion)) {
            cargarTabla();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Object seleccion = cbxnumero.getItemAt(anio); // crear un objeto selccion y me devuleve un item del combobox (tipo objeto)
        if (empresa.generar_Archivo((Integer) seleccion)) { // cateo objeto - entero crea un archivo con el item
            JOptionPane.showMessageDialog(null, "Se ha registrado correctamente!!", "OK!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Hubo un error", "ERROR", JOptionPane.ERROR);
        }
        cargarTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeActionPerformed
        // TODO add your handling code here:
        // Uso de etiquetas <b>: Para resaltar los títulos de cada sección.
        //Uso de etiquetas <br>: Para insertar saltos de línea y mejorar la legibilidad.

        lblPromedioTotal.setText("<html><b>PROMEDIO:</b> " + empresa.promedio().toString() + "</html>");
        lblTotalGastos.setText("<html><b>TOTAL GASTOS:</b> " + empresa.total(1) + "</html>");
        lblTotalVentas.setText("<html><b>TOTAL VENTAS:</b> " + empresa.total(0) + "</html>");

        Integer mayorVenta = empresa.mayor(anio, 0);
        Integer menorVenta = empresa.menor(anio, 0);
        Integer mayorGasto = empresa.mayor(anio, 1);
        Integer menorGasto = empresa.menor(anio, 1);

        lblVentasAltas.setText("<html><b>Mes con la venta más alta:</b><br>"
            + "Mes: " + MTableEmpresa.Meses.values()[mayorVenta].name() + "<br>"
            + "Venta: " + empresa.getDatos()[0][mayorVenta].toString() + "<br>"
            + "Gastos: " + empresa.getDatos()[1][mayorVenta].toString() + "</html>");

        lblVentasBajas.setText("<html><b>Mes con la venta más baja:</b><br>"
            + "Mes: " + MTableEmpresa.Meses.values()[menorVenta].name() + "<br>"
            + "Venta: " + empresa.getDatos()[0][menorVenta].toString() + "<br>"
            + "Gastos: " + empresa.getDatos()[1][menorVenta].toString() + "</html>");

        lblGastosAltos.setText("<html><b>Mes con el gasto más alto:</b><br>"
            + "Mes: " + MTableEmpresa.Meses.values()[mayorGasto].name() + "<br>"
            + "Gasto: " + empresa.getDatos()[1][mayorGasto].toString() + "<br>"
            + "Ventas: " + empresa.getDatos()[0][mayorGasto].toString() + "</html>");

        lblGastosBajos.setText("<html><b>Mes con el gasto más bajo:</b><br>"
            + "Mes: " + MTableEmpresa.Meses.values()[menorGasto].name() + "<br>"
            + "Gasto: " + empresa.getDatos()[1][menorGasto].toString() + "<br>"
            + "Ventas: " + empresa.getDatos()[0][menorGasto].toString() + "</html>");

        /*
        lblPromedioTotal.setText("PROMEDIO: " + empresa[anio].promedio().toString());
        lblTotalGastos.setText("TOTAL GASTOS: " + empresa[anio].total(1));
        lblTotalVentas.setText("TOTAL VENTAS: " + empresa[anio].total(0));
        Integer mayorVenta = empresa[anio].mayor(anio, 0);
        Integer menorVenta = empresa[anio].menor(anio, 0);
        Integer mayorGasto = empresa[anio].mayor(anio, 1);
        Integer menorGasto = empresa[anio].menor(anio, 1);
        lblVentasAltas.setText("<html>Mes con la venta mas alta fue: " + MTableEmpresa.Meses.values()[mayorVenta].name() + ", con: " + empresa[anio].getDatos()[0][mayorVenta].toString() + " y los gastos de ese mes fueron " + empresa[anio].getDatos()[1][mayorVenta].toString() + "</html>");
        lblVentasBajas.setText("<html>Mes con la venta mas bajo fue: " + MTableEmpresa.Meses.values()[menorVenta].name() + ", con: " + empresa[anio].getDatos()[0][menorVenta].toString() + " y los gastos de ese mes fueron " + empresa[anio].getDatos()[1][menorVenta].toString() + "</html>");
        lblGastosAltos.setText("<html>Mes con el gasto mas alta fue: " + MTableEmpresa.Meses.values()[mayorGasto].name() + ", con: " + empresa[anio].getDatos()[1][mayorGasto].toString() + " y las ventas de ese mes fueron " + empresa[anio].getDatos()[0][mayorGasto].toString() + "</html>");
        lblGastosBajos.setText("<html>Mes con el gasto mas bajo fue: " + MTableEmpresa.Meses.values()[menorGasto].name() + ", con: " + empresa[anio].getDatos()[1][menorGasto].toString() + " y las ventas de ese mes fueron " + empresa[anio].getDatos()[0][menorGasto].toString() + "</html>");
        */
    }//GEN-LAST:event_btnInformeActionPerformed

    private void btnSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecActionPerformed

        // TODO add your handling code here:
        cargarDatos();
    }//GEN-LAST:event_btnSelecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmEmpresa dialog = new FrmEmpresa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnInforme;
    private javax.swing.JButton btnSelec;
    private javax.swing.JButton btngenrar;
    private javax.swing.JComboBox<String> cbxnumero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGastosAltos;
    private javax.swing.JLabel lblGastosBajos;
    private javax.swing.JLabel lblPromedioTotal;
    private javax.swing.JLabel lblTotalGastos;
    private javax.swing.JLabel lblTotalVentas;
    private javax.swing.JLabel lblVentasAltas;
    private javax.swing.JLabel lblVentasBajas;
    private javax.swing.JTable tbltabla;
    private java.awt.TextField txtGastos;
    private java.awt.TextField txtVentas;
    // End of variables declaration//GEN-END:variables
}
