/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controller.utilidades.Utiles;
import javax.swing.JOptionPane;
import vistasmodeloTabla.ColorRenderer;
import vistasmodeloTabla.ColorRendererInverse;
//import vistasmodeloTabla.ColorTabla;

import vistasmodeloTabla.MtableMatriz;

/**
 *
 * @author InnoVausuario
 */
public class FrmMatriz extends javax.swing.JFrame {

    private MtableMatriz mTableMatriz; // definiendo 
    private Matriz matriz;
    private Integer fila = -1;
    private Integer columna = -1;

    private void cargarTabla() {
        //tblTabla.setDefaultRenderer(Object.class, new ColorTabla());
        mTableMatriz = new MtableMatriz();// crear la tabla
        tblTabla.getTableHeader().setVisible(false);
        mTableMatriz.setMatriz(matriz);
        tblTabla.setModel(mTableMatriz);
        for (int i = 0; i < this.matriz.getMtz()[0].length; i++) {
            if (i % 2 == 0) {
                tblTabla.getColumnModel().getColumn(i).setCellRenderer(new ColorRenderer());
            } else {
                tblTabla.getColumnModel().getColumn(i).setCellRenderer(new ColorRendererInverse());
            }
        }
        tblTabla.updateUI();
    }

    private void crear() {
        Integer m = (Integer) cbxM.getSelectedItem();
        Integer n = (Integer) cbxN.getSelectedItem();
        this.matriz = new Matriz();
        if (m != null && n != null) {
            this.matriz.crear(m, n);
            cargarTabla();
        } else {
            JOptionPane.showMessageDialog(null, "Llene todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    private boolean verificarModificar() {
        return (TxtModificar.getText().trim().isEmpty());
    }

    private boolean verificarMultiplo() {
        return (TxtMultiplo.getText().trim().isEmpty());
    }

    private void cargarDatos() {
        fila = tblTabla.getSelectedRow();
        columna = tblTabla.getSelectedColumn();
        if (fila >= 0) {
            if (matriz.getMtz()[fila][columna] != null) {
                TxtModificar.setText(matriz.getMtz()[fila][columna].toString());

            } else {
                fila = -1;
                TxtModificar.setText("");
                JOptionPane.showMessageDialog(null, "Seleccione un registro Valido", "ERROR", JOptionPane.ERROR);
            }
        } else {
            fila = -1;
            JOptionPane.showMessageDialog(null, "Llene todos los datos", "ERROR", JOptionPane.ERROR);
        }

    }

    private void modificar() {
        if (verificarModificar()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos ");
        } else {
            if (Utiles.validate(TxtModificar.getText().trim())) {
                Integer dato = (int) Utiles.transformarFloat(TxtModificar.getText().trim());

                if (fila != -1 && columna != -1) {
                    if (matriz.modificar(fila, columna, dato)) {
                        JOptionPane.showMessageDialog(null, "Se ha registrado correctamente", "OK!", JOptionPane.INFORMATION_MESSAGE);

                    } else {
                        JOptionPane.showMessageDialog(null, "Hubo un error al guardar o ya se guardaron los alumnos", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Ingrese un número", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

    }

    private void modificarMultiplo() {
        if (verificarMultiplo()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos ");
        } else {
            if (Utiles.validate(TxtMultiplo.getText().trim())) {
                Integer dato = (int) Utiles.transformarFloat(TxtMultiplo.getText().trim());
                matriz.ElimnarMultiplo(dato);
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese un número", "Error", JOptionPane.ERROR_MESSAGE);

            }
        }

    }

    /**
     * Creates new form FrmMatriz
     */
    public FrmMatriz() {

        initComponents();
        Matriz.cargaM(cbxM);
        Matriz.cargaM(cbxN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();
        TxtMultiplo = new javax.swing.JTextField();
        btnMultiplo = new javax.swing.JButton();
        btnPrimos = new javax.swing.JButton();
        btnAleatorio = new javax.swing.JButton();
        btnPar = new javax.swing.JButton();
        btnImpar = new javax.swing.JButton();
        btnCrear2 = new javax.swing.JButton();
        TxtModificar = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnSeleccionar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbxM = new javax.swing.JComboBox<>();
        cbxN = new javax.swing.JComboBox<>();

        jLabel4.setBackground(new java.awt.Color(102, 102, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("INFORME");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblTabla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 204), new java.awt.Color(0, 102, 204), null));
        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblTabla);

        TxtMultiplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMultiploActionPerformed(evt);
            }
        });

        btnMultiplo.setText("ELIMINAR MULTIPLOS");
        btnMultiplo.setEnabled(false);
        btnMultiplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiploActionPerformed(evt);
            }
        });

        btnPrimos.setText("ELIMINAR NUMEROS PRIMOS");
        btnPrimos.setEnabled(false);
        btnPrimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimosActionPerformed(evt);
            }
        });

        btnAleatorio.setText("GENERAR ALEATORIAMENTE");
        btnAleatorio.setEnabled(false);
        btnAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAleatorioActionPerformed(evt);
            }
        });

        btnPar.setText("ELIMINAR NUMEROS PARES");
        btnPar.setEnabled(false);
        btnPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParActionPerformed(evt);
            }
        });

        btnImpar.setText("ELIMINAR NUMEROS IMPARES");
        btnImpar.setEnabled(false);
        btnImpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImparActionPerformed(evt);
            }
        });

        btnCrear2.setText("CREAR");
        btnCrear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrear2ActionPerformed(evt);
            }
        });

        TxtModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtModificarActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnSeleccionar.setText("SELECCIONAR");
        btnSeleccionar.setEnabled(false);
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(51, 102, 0));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MATRIZ");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setOpaque(true);

        cbxM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnImpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPrimos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMultiplo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtMultiplo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxM, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxN, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrear2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TxtModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAleatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSeleccionar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrear2)
                        .addGap(33, 33, 33)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAleatorio)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(TxtMultiplo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMultiplo)
                        .addGap(27, 27, 27)
                        .addComponent(btnPar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrimos)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtMultiploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMultiploActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMultiploActionPerformed

    private void TxtModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtModificarActionPerformed

    private void btnCrear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrear2ActionPerformed
        // TODO add your handling code here:
        crear();
        btnModificar.setEnabled(true);
        btnImpar.setEnabled(true);
        btnPar.setEnabled(true);
        btnPrimos.setEnabled(true);
        btnAleatorio.setEnabled(true);
        btnMultiplo.setEnabled(true);
        btnSeleccionar.setEnabled(true);

    }//GEN-LAST:event_btnCrear2ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        modificar();
        cargarTabla();

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnMultiploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiploActionPerformed
        // TODO add your handling code here:
        modificarMultiplo();
        cargarTabla();
    }//GEN-LAST:event_btnMultiploActionPerformed

    private void btnParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParActionPerformed
        // TODO add your handling code here:
        matriz.ElimnarPar();
        cargarTabla();
    }//GEN-LAST:event_btnParActionPerformed

    private void btnImparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImparActionPerformed
        // TODO add your handling code here:
        matriz.ElimnarImpar();
        cargarTabla();

    }//GEN-LAST:event_btnImparActionPerformed

    private void btnAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAleatorioActionPerformed
        // TODO add your handling code here:
        matriz.generarMatrizAleatorio();
        cargarTabla();


    }//GEN-LAST:event_btnAleatorioActionPerformed

    private void btnPrimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimosActionPerformed
        // TODO add your handling code here:
        matriz.EliminarPrimo();
        cargarTabla();


    }//GEN-LAST:event_btnPrimosActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
        cargarDatos();
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMatriz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtModificar;
    private javax.swing.JTextField TxtMultiplo;
    private javax.swing.JButton btnAleatorio;
    private javax.swing.JButton btnCrear2;
    private javax.swing.JButton btnImpar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMultiplo;
    private javax.swing.JButton btnPar;
    private javax.swing.JButton btnPrimos;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JComboBox<String> cbxM;
    private javax.swing.JComboBox<String> cbxN;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTabla;
    // End of variables declaration//GEN-END:variables
}
